org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.offline=false
android.useAndroidX=true
android.nonTransitiveRClass=true
# Solo si no puedes mover el proyecto a una ruta ASCII
# android.overridePathCheck=true
